import { test } from "../fixtures/hooks-fixture"
import { expect } from "@playwright/test";

test("Add new employee is added successfully", {
    tag: ['@pim','@visual'],
    annotation: {
        type: 'feature- Test case link',
        description: 'Adding new employee in PIM module url of the link '
    }
}, async ({ goToUrl, leftNavPannel, pimPage }) => {
    await leftNavPannel.navigateToPIM();
    await expect(leftNavPannel.pimTabHeader).toBeVisible();
    await pimPage.addNewEmployee("John", "Doe");
    expect(await pimPage.pullAutogeneratedEmployeeId()).toBe('John');
})
test("Add new employee is added successfully with test Step integration", {
    tag: ['@pim'],
    annotation: {
        type: 'feature- Test case link',
        description: 'Adding new employee in PIM module url of the link '
    }
}, async ({ goToUrl, leftNavPannel, pimPage }) => {
    await test.step("Navigate to PIM module", async () => {
        await leftNavPannel.navigateToPIM();
        await expect(leftNavPannel.pimTabHeader).toBeVisible();
    })
    await test.step("Add new employee", async () => {
        await pimPage.addNewEmployee("John", "Doe");
        expect(await pimPage.pullAutogeneratedEmployeeId()).toBe('John');
    })



})

test("Visual Testing - for brand logo", {
    tag: ['@pim', ],
    annotation: {
        type: 'feature- Test case link',
        description: 'Visual testing for brand logo in PIM module url of the link '
    }
}, async ({ goToUrl, leftNavPannel, pimPage }) => {
    await test.step("Visual Validation of Brand Logo", async () => {
        await expect(leftNavPannel.brandLogo).toHaveScreenshot('brand-logo.png');
        await expect(leftNavPannel.sideNavPanel).toHaveScreenshot('side-nav-panel.png');

    })


})