import { Page, Locator, expect } from "@playwright/test";

export class PimPage {
    readonly page : Page;
    readonly addEmployeeButton : Locator;
    readonly firstNameInput: Locator;
    readonly lastNameInput: Locator;
    readonly saveButton: Locator;

    constructor(page: Page){
        this.page = page;
        this.addEmployeeButton = page.getByRole('button', { name: ' Add' })
        this.firstNameInput = page.getByRole('textbox', { name: 'First Name' });
        this.lastNameInput = page.getByRole('textbox', { name: 'Last Name' });
        this.saveButton = page.getByRole('button', { name: 'Save' });   
    }

    async addNewEmployee(firstName: string, lastName: string){
        await this.addEmployeeButton.click();
        await this.firstNameInput.fill(firstName);
        await this.lastNameInput.fill(lastName);
        await this.saveButton.click();
    }
    
    async pullAutogeneratedEmployeeId(): Promise<string> {
        return await this.firstNameInput.inputValue();
    }
}
